name: Deploy Java App and MySQL to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
           java-version: '21'
           distribution: 'temurin' # Use Temurin (Adoptium) JDK

      - name: Build Java application
        run: |
          mvn clean package -DskipTests

      - name: Copy files to EC2s
        uses: appleboy/scp-action@master
        with:
          host: 13.235.232.46
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/security-server-0.0.1-SNAPSHOT.jar,Dockerfile,docker-compose.yml"
          target: "/home/ec2-user/app"

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.235.232.46
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            docker-compose down
            docker-compose up -d